// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddFriend(ctx context.Context, arg AddFriendParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	GetOnesFriends(ctx context.Context, arg GetOnesFriendsParams) ([]GetOnesFriendsRow, error)
	GetUserByName(ctx context.Context, username string) (User, error)
}

var _ Querier = (*Queries)(nil)
